# Generated by Django 6.1.1 on 2026-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(null=True),
        ),
    ]
